---
# Checks: 2.1.1 – 2.1.6, NS_STD_011, NS_STD_022

- name: "2.1.x / NS_STD_011/022 — Aplicar password policy"
  f5networks.f5_modules.bigip_auth_password_policy:
    min_length:          "{{ f5_password_min_length }}"
    required_lower:      "{{ f5_password_required_lower }}"
    required_upper:      "{{ f5_password_required_upper }}"
    required_special:    "{{ f5_password_required_special }}"
    password_memory:     "{{ f5_password_memory }}"
    policy_enforcement:  "{{ f5_password_enforcement }}"
    max_duration:        "{{ f5_password_max_duration }}"
    expiration_warning:  "{{ f5_password_expiration_warning }}"
    provider:            "{{ f5_provider }}"
